import { t } from 'i18next'
import Head from 'next/head'

export default function Home() {
   

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home">
        <div className="container">
          <h1>{t('home_text')}</h1>
        </div>

      </div>

    </>
  )
}
